### ISSUE TITLE
Lots of 404s after running `yarn dev` 

### ISSUE THREAD

**Issue by dmackerman** [markgoetz/jankpile#1]
<img width="2308" alt="image" src="https://user-images.githubusercontent.com/289938/175988685-87635482-9adf-41b9-9084-b54b05898288.png">

Looks like there is trouble connecting to the Netlify functions/Scryfall API. Let me know how to proceed. :)

**Comment by markgoetz** [comment]
I think I saw what the issue is and I just pushed a new commit.  Can you pull from `master` and try again?

**Comment by dmackerman** [comment]
Hmm, no dice. 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/289938/176077472-e7e7da28-dfbf-4cf9-8435-a13962aaa611.png">

Is `yarn dev` how you start up? 

`yarn start` spins up`localhost:3000`, but I still get 404s.

Do I need to configure this to target my Netlify account? (I do have one)

**Comment by dmackerman** [comment]
Forked the repo and created my own Netlify deploy and everything works! Thanks @markgoetz.
